// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngyyteewquucikoptsiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5neXl0ZWV3cXV1Y2lrb3B0c2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTA0MTgsImV4cCI6MjA2NDI4NjQxOH0.9koXfs689WX9O0UHIa2RTSfvwFrjoVLH3ChjwPbECJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);